parameters:
  glabs.json_api.parameters.servers: ~

services:
    glabs.json_api.services.api:
        class: GrailleLabs\JsonApiBundle\Services\JsonApiService
        arguments:
            - '@service_container'